### ISSUE TITLE
Arduino shuts down when connected to an external power supply

### ISSUE THREAD

**Issue by canadianbimmer** [keivan-amini/Automated-Grow-Box-for-mushrooms-project#1]
Hi Keivan,
Very nice project btw! I tried to make a closed box with the same components as you for an control center for a grow box. I downloaded the code and library into Arduino IDE. The code run smoothly and everything seems to work. The screen is showing all the information and I can hear the relay clicking. So I uploaded the code into the arduino and connect the Arduino to a power supply. At first, it starts up, then after a few moments, the Arduino shuts down and starts up again to crash again...I tried to look at some forum about this issue. Some talks about a power supply issue, but I tried with 3 different ones with different amp so it doesn't seem to be a weak power supply or a defective one. Had you some problem with this too? If not, do you know what could it be? Because when connected to my computer the Arduino never crashes.
Thank you!
Ludovic

**Comment by keivan-amini** [comment]
Hey Ludovic 😄 
thank you for reaching out!

What kind of power supply are you using?

In my project, as far as I remember, Arduino UNO was directly connected with a battery. It's hard to see from the uploaded photos, but I noticed it while zooming a bit.
![battery](https://github.com/keivan-amini/Automated-Grow-Box-for-mushrooms-project/assets/100836058/50eb80a4-eff4-4b26-9d01-ee0b0002a81c)
If I remember correctly, it was a 9V battery such this one in the [link](https://qizzle.co.nz/energizer-9v-alkaline-max-battery-pkt-1.html). 

In your situation, it seems likely that there's a discrepancy between the permitted voltage of the Arduino board you're using and the actual voltage you're supplying. I'd suggest double-checking these specifications to ensure compatibility. 

Let me know if this resolves the issue!

Best,
Keivan

**Comment by canadianbimmer** [comment]
Hi Keivan,

I am using a 12V 2A with the dc 2.1mm power jack connector.

I think you're right, I didn't see the battery at first but maybe for some reasons, the power allowed by the Arduino with the dc power jack connector, can be limited and exceed the capacity of the Arduino, causing it to shut down. I continued my research on the forum but about 4-channel relays, and it seems that it's a good practice to power the relay with an external power supply (the ground must be shared with the Arduino). So I'm thinking of using a 5V buck converter to split my power input with one part going into the Vin for the Arduino and the second, to go into the buck converter for a 5V output to the relay's power input. This way, the Arduino still uses the pin to control the relays but does not power them. I've ordered the parts and will keep you posted!

Thanks a lot!

Ludovic

**Comment by canadianbimmer** [comment]
Hi Keivan,

I've finally received the buck converter and everything is working fine! Powering the relay from a source other than the Arduino itself with a common ground so that the Arduino pins work with the relay, was a good solution.

Thanks again for your help and your time!

Ludovic
*Here are a few photos of the box I made for the electronics (PS: The wiring is a mess at the moment).
![IMG_8862](https://github.com/keivan-amini/Automated-Grow-Box-for-mushrooms-project/assets/118410276/650aaf2d-4ca2-464e-89e0-182fee98fa91)
![IMG_8863](https://github.com/keivan-amini/Automated-Grow-Box-for-mushrooms-project/assets/118410276/418f1f70-1f56-4f5d-bc94-bbff467a68c8)

**Comment by keivan-amini** [comment]
Good job Ludovic! Super happy that everything works fine :)
